# Generated by Django 4.1.2 on 2023-03-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profilepics/default-propic.png', upload_to='profilepics'),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('likes', models.ManyToManyField(related_name='likes', to='socials.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socials.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('cmt_likes', models.ManyToManyField(related_name='cmt_likes', to='socials.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socials.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socials.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='socials.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr', to='socials.profile')),
            ],
            options={
                'unique_together': {('user', 'followers')},
            },
        ),
    ]
