# Generated by Django 4.1.2 on 2023-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_alter_followers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
