# Generated by Django 4.1.2 on 2023-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0018_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='socials.profile'),
        ),
    ]
