# Generated by Django 4.1.2 on 2023-03-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0020_alter_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
